### ISSUE TITLE
How to run environmental-dependent models with a sample of trees

### ISSUE THREAD

**Issue by KaterynPino** [hmorlon/PANDA#28]
Hello, 

I want to fit the environmental-dependent models in RPANDA, but with a sample of trees, but I don't know-how. All the examples I found are with a single tree. There is some script to do this?. A lot of thanks!

Cheers, 

Kateryn

**Comment by FabienCondamine** [comment]
Dear Kateryn,

One simple way to do this is as follows:

missing.lineages <- # a numerical value for your total clade species diversity
trees <- read.tree("Posteriors_trees.tre") #Can be read.nexus() especially if posterior trees come from a BEAST analysis
subsampled.trees <- sample(trees, 100)

for (i in 1:length(subsampled.trees))
{
	tree <- subsampled.trees[[i]]
	tot_time <- max(node.age(tree)$ages)
	f <- Ntip(tree)/(Ntip(tree)+missing.lineages)
	cond = "crown"
	
print("BTempVar EXPO")
f.lamb<-function(t,x,y){y[1]*exp(y[2]*x)}
f.mu<-function(t,x,y){0}
lamb_par<-c(0.1,0.0)
mu_par<-c()
cst.lamb=F; cst.mu=T; expo.lamb=F; expo.mu=F; fix.mu=T

	tree_BTempVar_EXPO <- fit_env(tree, env_data, tot_time, f.lamb, f.mu,lamb_par, mu_par, f=f, cst.lamb=cst.lamb, cst.mu=cst.mu, expo.lamb=expo.lamb, expo.mu=expo.mu, fix.mu=fix.mu, cond=cond, dt=1e-3)
	print(tree_BTempVar_EXPO)
}

Of course, you need to create an object (list, vector, matrix) to store the results for each tree of your distribution. Also, you need to load the temperature data, here named env_data in the fit_env function (e.g. data(InfTemp)).

I hope this helps. Don't hesitate if you have any questions.

Best regards,

**Comment by KaterynPino** [comment]
Dear Fabien,

I appreciate your response. It has been a great help. 

But, now I have a problem with the initial parameters (Error in optim(init, optimLH, method = meth function cannot be evaluated at initial parameters). This is weird because I ran a bunch of different models of time dependency (fit_bd function) and everything ok. Nevertheless, when I traying with environmental dependency models (fit_env function) the analysis stops with this error after ran the first 5 or 10 samples trees. I try changing the initial parameters several times but it doesn't work. What can I do?. 

A lot of thanks!

Best regards,

**Comment by JClavel** [comment]
Hi Kateryn,

Just to check, what is the height of your tree? (e.g. max(nodeHeights(phylo)))
The age must be < to the total length (age) of the climatic curve.

Regards,

Julien

________________________________
De : KaterynPino <notifications@github.com>
Envoyé : dimanche 23 février 2020 16:10
À : hmorlon/PANDA <PANDA@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [hmorlon/PANDA] How to run environmental-dependent models with a sample of trees (#28)


Dear Fabien,

I appreciate your response. It has been a great help.

But, now I have a problem with the initial parameters (Error in optim(init, optimLH, method = meth function cannot be evaluated at initial parameters). This is weird because I ran a bunch of different models of time dependency (fit_bd function) and everything ok. Nevertheless, when I traying with environmental dependency models (fit_env function) the analysis stops with this error after ran the first 5 or 10 samples trees. I try changing the initial parameters several times but it doesn't work. What can I do?.

A lot of thanks!

Best regards,

**Comment by KaterynPino** [comment]
Hi Julien, 

You are right, everything it's ok now. A lot of thanks!

Regards, 

Kate
