### ISSUE TITLE
error when running fit_t_comp on seemingly random trees

### ISSUE THREAD

**Issue by alexsla** [hmorlon/PANDA#33]
I've been attempting to fit MC models on a set of simulated phylogenies, all simulated using the same parameters. On seemingly random trees, the function fails and brings up the following error:

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent 

By following the traceback, it seems the error occurs somewhere during the optimisation process when running fitTipData internally, but I can't figure out what is causing the problem, and why other trees simulated under the same parameters don't break the function.

I'm attaching a zip file with two RDS files: the simulated tree (tree.RDS) and the named vector of trait values (traits.RDS) I used to try to run the function.

[data.zip](https://github.com/hmorlon/PANDA/files/5559401/data.zip)

Thank you,
Alex

**Comment by jonathanpdrury** [comment]
Hey Alex,

I couldn't reproduce the error with those data files--I got the following output:

> fit_t_comp(tree,traits,model="MC")
$LH
[1] -104.7983

$aic
[1] 215.5965

$aicc
[1] 216.4854

$free.parameters
[1] 3

$sig2
[1] 0.9284882

$S
[1] -0.04798165

$z0
[1] 9.228093

$convergence
[1] 0

Perhaps there is another example? Fwiw, I'm running R 4.0.3 and RPANDA v1.9

**Comment by alexsla** [comment]
Hi Jonathan,

I'm running the same versions of R and RPANDA. Attached is another set of tree+traits on which it fails.
[data1.zip](https://github.com/hmorlon/PANDA/files/5561020/data1.zip)

**Comment by jonathanpdrury** [comment]
I was able to reproduce the issue this time, although the function failed with a different error: 
"Error in newSigma[paste, 1:(paste - 1)] <- Sigma[copy, 1:(paste - 1)] : 
  replacement has length zero"

This occurs because several nodes in the tree occur at precisely the same time (i.e., some values of diff(branching.times(tree)[order(branching.times(tree))]) == 0). The easiest solution would be to add a very small amount of random jitter to the branch lengths, which should fix the error that I pasted above (though I'm not sure about the 'dimnames' error--I couldn't reproduce that).

**Comment by alexsla** [comment]
Thanks Jonathan! I tried that and it worked, seems like that was indeed the problem with all the trees that failed.

**Comment by jonathanpdrury** [comment]
Great, glad to hear it!
